# Unit I: Review of Statistics and Probability {-}

We assume that you are familiar with performing statistical inference at the introductory level; this includes graphical and numerical summaries, inference (confidence intervals and hypothesis testing) for a mean response, simple linear regression to characterize the relationship between two quantitative variables, and analysis of variance for comparing the mean response across groups.  We also assume this introduction to statistical inference includes major concepts like the importance of study design in interpreting results, modeling the sampling distribution of a statistic (or standardized test statistic) using a classical approach (probability) or a modern empirical approach (bootstrapping).  When viewed as a list of topics like this, the introductory course can feel overwhelming.  In this first unit, we provide a brief review of these topics through the lens of a unifying framework for inference.  Our goal is to provide a "story" that will be further developed in the remainder of the text.

We also provide a brief introduction to the essential elements of probability.  Probability is the field within mathematics that studies and models random processes.  In contrast, Statistics is a discipline separate from mathematics that uses data to make inference on a population.  Like many other disciplines (e.g., Engineering and the Sciences), while Statistics is a separate discipline, the theory underlying the discipline relies heavily on mathematics; for Statistics, probability plays a pivotal role.  We personally favor introducing statistical concepts with minimal reference to probability, instead choosing to build on students' intuition of probability.  In line with that philosophy, we will strive to introduce statistical approaches within the biological sciences with minimal probability.  However, we do need a little more machinery to address these topics than is necessary for an introductory course.  As a result, this unit includes elements of probability essential to our future development of statistical methods.  We choose to place it here so that it is easily referenced from multiple units in the future and to emphasize that probability is separate from statistics.
