# Unit IV: Models for Repeated Measures {-}

The conditions we impose on the data generating process impact the model of the sampling distribution of our parameter estimates, and the model for the sampling distribution is necessary for performing inference.  At times, the conditions we are willing to impose are driven by the data collection procedure.  In this unit, we consider data that result from study designs that lead to collections of observations being associated with one another (beyond what can be explained by the predictors in the model).  This correlation between observations must be appropriately modeled if we want to model the sampling distribution of our parameter estimates.

Specifically, this unit considers the topic of repeatedly measuring the response.  This could be the result of a study design that requires the response be measured routinely on the same participants (a "pre-post" study, for example); or, it could be the result of a study design that first enrolls entire families and then records the response for each member of the family.  In the first example, it is reasonable to believe the responses recorded on the same participant are associated with one another in some way; in the second example, it is reasonable to believe responses recorded on members of the same family are associated with one another in some way.  Understanding how to incorporate this relationship in the model allows us to conduct such studies, which often have more power to detect effects of interest.
