# Proportional Hazards Model {#sec-surv-cph}

{{< include _setupcode.qmd >}}

Regression models allow us to quantify the effect of a set of predictors on the distribution of the response.  While there are various regression methods for survival analysis, perhaps the most common is the Cox Proportional Hazards model, which we discuss in this chapter.

As the name of this chapter hints at, our modeling approach depends on the assumption of proportional hazards.

:::{#def-proportional-hazards}
## Proportional Hazards
Let $\lambda_1(t)$ and $\lambda_2(t)$ represent the hazard functions for two different groups.  The assumption of proportional hazards states that

$$\frac{\lambda_2(t)}{\lambda_1(t)} = e^{\gamma}$$

for some fixed $\gamma$.  That is, the ratio of the hazard functions does not depend on time.  
:::

The reason for choosing to exponentiate the constant in @def-proportional-hazards is because the hazard ratio must always be positive (since each hazard is positive for all values of $t$).  This allows $\gamma$, the natural logarithm of the hazard ratio, to play a role similar to the log-odds ratio (from logistic regression in @sec-nlm-logistic).  When $\gamma = 0$, the hazard ratio is 1 and the two hazard functions are equal across all time (meaning the corresponding survival curves are equal across all time).  When $\gamma > 0$, the hazard ratio is larger than 1 and group 2 is more likely to experience the event (survival curve sits below) compared with group 1.  When $\gamma < 0$, the hazard ratio is below 1 and group 2 is less likely to experience the event (survival curve sits above) compared with group 1.

:::{.callout-warning}
Proportional hazards is an assumption.  It is not guaranteed to hold in any setting; however, it is a useful simplifying assumption and often does hold at least reasonably well.
:::

Early in this unit, we alluded to the idea that some characterizations of the distribution are easier to model than others.  When censoring is present, it turns out that modeling the hazard turns out to be easier than modeling the survival function directly.  Therefore, we want our model to allow the hazard function to depend upon predictors.  

:::{.callout-note}
Remember, a key idea in regression modeling is characterizing the distribution of the response through its parameters.  We have spent a great deal of time in the text characterizing the mean and variance of the response with our regression models.  Here, instead of the mean survival time, we are modeling the hazard function.
:::

:::{.callout-note}
Note that unlike modeling the mean response in which our model specifies a single value (the mean response) for a given set of predictors, in survival analysis, we are modeling an entire function.  That is, for a given set of predictors, we are specifying the hazard _function_ over time.
:::

We could model the hazard function under parametric assumptions (assuming a particular distribution for the event times and censor times, for example).  However, Cox developed a semiparametric model that dominates the literature in the biological sciences.

:::{#def-cph}
## Cox Proportional Hazards Model
The proportional hazards model (or Cox proportional hazards model, or PH model, or Cox PH model) is a model for the hazard function that enforces the assumption of proportional hazards; it has the following form:
  
$$\lambda\left(t \mid (\text{Predictors})_i\right) = \lambda_0(t) e^{\sum\limits_{j=1}^{p} \beta_j (\text{Predictor } j)_i},$$

where the form of $\lambda_0(t)$, known as the baseline hazard, is not specified.
:::

This model separates the hazard function into a function of time alone (the baseline hazard) and a function of the predictors alone (the exponent).  Since the baseline hazard is not specified, this is a semiparametric model; if this form were specified, we would have a fully parametric model.  The baseline hazard function represents the hazard function when all predictors take the value of 0.  That is, instead of a single intercept, we have a type of "intercept-function."  

As a result of the product of the baseline hazard with the exponential term, the predictors serve to scale the hazard function, making this a multiplicative model instead of additive.  The name comes from the fact that the model enforces the assumption of proportional hazards.  To see this, consider a simple model with only two predictors.  Suppose one group of subjects has predictor values $a$ and $b$, respectively.  Then, their hazard function has the form

$$\lambda_1(t \mid \text{Predictors}) = \lambda_0(t) e^{\beta_1 a + \beta_2 b}.$$

Let a second group of subjects have predictor values $a + 1$ and $b$, increasing the first predictor by 1 unit.  Observe that their hazard function is

$$\lambda_2(t \mid \text{Predictors}) = \lambda_0(t) e^{\beta_1 (a + 1) + \beta_2 b}.$$

The baseline hazard function does not depend on the predictor values and so is shared between both groups.  Now, the hazard ratio of group 2 compared with group 1 is

$$
\begin{aligned}
  \text{HR} &= \frac{\lambda_2(t \mid \text{Predictors})}{\lambda_1(t \mid \text{Predictors})} \\
    &= \frac{\lambda_0(t) e^{\beta_1 a + \beta_1 + \beta_2 b}}{\lambda_0(t) e^{\beta_1 a + \beta_2 b}} \\
    &= e^{\beta_1},
\end{aligned}
$$

which does not depend on time $t$ and therefore suggests the hazard functions are proportional across time.  Further, this derivation provides an interpretation for the parameters in the model.

:::{#def-hr}
## Interpretation of Parameters for the Proportional Hazards Model
Consider modeling the hazard function using the proportional hazards model of @def-cph.  The coefficient on the $j$-th predictor $\beta_j$ is the log-hazard ratio associated with a one-unit increase in the $j$ predictor, holding all other predictors fixed.
:::

Of course, we do not observe the actual values of the parameters; therefore, we estimate the parameters and therefore estimate the hazard function.  This is done via a partial likelihood, the details of which are beyond the scope of this text; it was this partial likelihood, however, that made the above model useful in practice.  Partial likelihood allows us to estimate the parameters, and even model the sampling distribution of these estimates, without needing to specify the baseline hazard function!

The simplicity of the Cox PH model has led to wide use.  However, its apparent simplicity is also the source of many common mistakes when using the model in practice.  

:::{.callout-note}
## Common Errors when Working with the Proportional Hazards Model
The following are common mistakes made by practitioners working with the proportional hazards model (@def-cph).

  - Using predictors that were gathered after baseline or the assignment of the treatment of interest.  If we observe something after we "start the clock," then its very observation implies the subject is event-free at its observation.
  - Forgetting the proportional hazards assumption implies one curve is superior regardless of time.  If we estimate the survival curves from a proportional hazards model, one treatment group will always be superior to the other (though the difference may be statistically indiscernible).  This is because the proportional hazards assumption states that one survival curve always sits above the other.
  - Neglecting that this framework can be generalized to handle repeated outcomes and time-dependent predictors.  In our formulation, we do not allow the predictors to depend on time, but this framework generalizes nicely to do so (or multiple types of events).  Some researchers perform unnecessary simplifications when the method should be generalized instead.
:::

We have seen the appeal of semi-parametric models throughout the course.  Given enough data, they often provide efficient estimation without requiring many conditions on the data generating process.  While the proportional hazards model does avoid explicitly specifying the form of the survival distribution, it does carry certain conditions.

:::{.callout-note}
## Conditions of the Proportional Hazards Model
When we model the hazard using the proportional hazards model (@def-cph), we impose the following conditions:

  - The portion of the model involving the predictors is correctly specified.
  - The predictors are linearly related to the log-hazard function.
  - The affect of changing a predictor in isolation results in proportional hazards; this is enforced by the model.  It implies that survival curves should not cross for different groups.
  - The censoring time is independent of the survival time.
:::

As with other forms of regression models, residual plots can be created to assess the first three conditions.  The final condition must be assessed by discipline expertise.  The complication is that there is not a single definition of a residual with time-to-event data.  And, different types of residuals are useful for assessing different conditions.  While beyond the scope of this text, we want to note that there are methods for relaxing many of these conditions while still remaining in the same general framework, making the proportional hazards model extremely flexible.  For example, we could use splines to relax the "linearity" condition stated above.

