<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistical Modeling for the Biological Sciences - 13&nbsp; The Language of Repeated Measures</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./04c-rm-mixed-models.html" rel="next">
<link href="./04a-rm.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="mystyles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./04a-rm.html">Unit IV: Models for Repeated Measures</a></li><li class="breadcrumb-item"><a href="./04b-rm-terminology.html"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The Language of Repeated Measures</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Biostatistics</a> 
        <div class="sidebar-tools-main">
    <a href="./ma482-text.pdf" rel="" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./01a-review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit I: Review of Statistics and Probability</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01b-statistical-process.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Overview of the Statistical Process</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01c-distributional-quartet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Distributional Quartet</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01d-essential-probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Essential Probability</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./02a-glm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit II: General Linear Model</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02b-glm-model-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">General Linear Model Framework</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02c-glm-assessing-conditions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Assessing the Conditions for the General Linear Model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02d-glm-unifying-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">The General Linear Model as a Unifying Framework</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./03a-modeling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit III: General Modeling Techniques</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03b-modeling-related-predictors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Addressing Relationships Between Predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03c-modeling-categorical-predictors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Incorporating Categorical Predictors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03d-modeling-interactions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Allowing Effect Modification (Interaction Terms)</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03e-modeling-linear-hypotheses.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">General Linear Hypothesis Test</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03f-modeling-large-sample-theory.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Large Sample Theory</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03g-modeling-splines.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Modeling Curvature (Splines)</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./04a-rm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit IV: Models for Repeated Measures</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04b-rm-terminology.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The Language of Repeated Measures</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04c-rm-mixed-models.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Mixed Effects Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04d-rm-gee.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Generalized Estimating Equations</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./05a-nlm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit V: Nonlinear Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05b-nlm-model-framework.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Nonlinear Model Framework</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05c-nlm-heteroskedasticity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Relaxing the Constant Variance Condition</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05d-nlm-logistic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Logistic Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05e-nlm-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Model Selection</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05f-nlm-estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Estimation Details for Nonlinear Models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05g-nlm-rm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Nonlinear Models with Repeated Measures</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./06a-surv.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unit VI: Survival Analysis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06b-surv-terminology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">The Language of Survival Analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06c-surv-censoring.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Censoring</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06d-surv-basic.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Basic Estimation and Inference</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06e-surv-cph.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Proportional Hazards Model</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Glossary</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#importance-of-study-design" id="toc-importance-of-study-design" class="nav-link active" data-scroll-target="#importance-of-study-design"><span class="header-section-number">13.1</span> Importance of Study Design</a></li>
  <li><a href="#studies-with-repeated-measures" id="toc-studies-with-repeated-measures" class="nav-link" data-scroll-target="#studies-with-repeated-measures"><span class="header-section-number">13.2</span> Studies with Repeated Measures</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-rm-terminology" class="quarto-section-identifier"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">The Language of Repeated Measures</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="importance-of-study-design" class="level2" data-number="13.1">
<h2 data-number="13.1" class="anchored" data-anchor-id="importance-of-study-design"><span class="header-section-number">13.1</span> Importance of Study Design</h2>
<p>Study design is too often separated from the statistical analysis that follows. However, in addition to informing the conclusions we draw regarding the data, the study design helps in choosing an appropriate analysis to address the question of interest. As an example, consider the following study reported in <span class="citation" data-cites="Vittinghoff2012">Vittinghoff et al. (<a href="references.html#ref-Vittinghoff2012" role="doc-biblioref">2012</a>)</span>.</p>
<div id="exm-rm-enzyme" class="theorem example">
<p><span class="theorem-title"><strong>Example 13.1 (Digestive Enzymes) </strong></span>The ability of the bowels to properly absorb nutrients can be impacted by a lack of digestive enzymes. This presents as excess fat in the feces, which is in turn treated with pancreatic enzyme supplements. A study was conducted comparing three forms of a particular enzyme supplement; these were compared to no supplement (placebo) as a control. Participants were given the supplement to take for a specified length of time; then, the amount of fecal fat (g/day) present was recorded. Interest is in determining if the amount of fecal fat produced, on average, differs for any of the treatments.</p>
</div>
<p>Suppose we are given the data in <a href="#tbl-rm-enzyme-data-table">Table&nbsp;<span>13.1</span></a> to address the question posed in <a href="#exm-rm-enzyme">Example&nbsp;<span>13.1</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-rm-enzyme-data-table" class="anchored">
<div class="table-responsive">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<caption>Table&nbsp;13.1: Fecal fat (g/day) present in participants given a pancreatic enzyme supplement.</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Placebo</td>
<td style="text-align: right;">44.5</td>
<td style="text-align: right;">33.0</td>
<td style="text-align: right;">19.1</td>
<td style="text-align: right;">9.4</td>
<td style="text-align: right;">71.3</td>
<td style="text-align: right;">51.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tablet</td>
<td style="text-align: right;">7.3</td>
<td style="text-align: right;">21.0</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">4.6</td>
<td style="text-align: right;">23.3</td>
<td style="text-align: right;">38.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Coated Capsule</td>
<td style="text-align: right;">12.4</td>
<td style="text-align: right;">25.6</td>
<td style="text-align: right;">22.0</td>
<td style="text-align: right;">5.8</td>
<td style="text-align: right;">68.2</td>
<td style="text-align: right;">52.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Uncoated Capsule</td>
<td style="text-align: right;">3.4</td>
<td style="text-align: right;">23.1</td>
<td style="text-align: right;">11.8</td>
<td style="text-align: right;">4.6</td>
<td style="text-align: right;">25.6</td>
<td style="text-align: right;">36.0</td>
</tr>
</tbody>
</table>
</div>
</div>


</div>
</div>
<p>Consider the following generalized linear model to describe the data generating process:</p>
<p><span id="eq-rm-terminology-glm"><span class="math display">\[(\text{Fat})_i = \beta_0 + \beta_1 (\text{Tablet})_i + \beta_2 (\text{Coated})_i + \beta_3 (\text{Uncoated})_i + \varepsilon_i, \tag{13.1}\]</span></span></p>
<p>where</p>
<p><span class="math display">\[
\begin{aligned}
  (\text{Tablet})_i
    &amp;= \begin{cases}
      1 &amp; \text{if i-th observation corresponds to supplement in tablet form} \\
      0 &amp; \text{otherwise} \end{cases} \\
  (\text{Coated})_i
    &amp;= \begin{cases}
      1 &amp; \text{if i-th observation corresponds to supplement in coated form} \\
      0 &amp; \text{otherwise} \end{cases} \\
  (\text{Uncoated})_i
    &amp;= \begin{cases}
      1 &amp; \text{if i-th observation corresponds to supplement in uncoated form} \\
      0 &amp; \text{otherwise} \end{cases} \\
\end{aligned}
\]</span></p>
<p>are indicator variables capturing the impact of the categorical treatment group. Our question of interest is captured by the testing</p>
<p><span class="math display">\[H_0: \beta_1 = \beta_2 = \beta_3 = 0 \qquad \text{vs.} \qquad H_1: \text{At least one } \beta_j \text{ differs}.\]</span></p>
<p>This analysis demonstrates no evidence (p = 0.168) the average amount of fecal fat differs for any of the supplement forms (see <a href="#fig-rm-terminology-enzyme-plot">Figure&nbsp;<span>13.1</span></a>).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-rm-terminology-enzyme-plot" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./images/fig-rm-terminology-enzyme-plot-1.png" class="img-fluid figure-img" style="width:80.0%" alt="Side-by-side boxplots with raw data overlaid."></p>
<figcaption class="figure-caption">Figure&nbsp;13.1: Fecal fat (g/day) present in participants given a pancreatic enzyme supplement when we assume 24 independent participants.</figcaption>
</figure>
</div>
</div>
</div>
<p>Of course, the above analysis is predicated on the data being consistent with the conditions for the classical regression model. For example, it seems reasonable to assume that the fecal fat present in one subject is independent of the fecal fat present in any other subject once we have accounted for the type of supplement. Therefore, it seems reasonable that any two fecal fat measurements above are independent once we have accounted for the type of supplement received. This, however, follows from how we assumed the data was collected — that each measurement is from a different subject.</p>
<p>Let’s reconsider the above example but add a little more context to the study design.</p>
<div id="exm-rm-enzyme-expanded" class="theorem example">
<p><span class="theorem-title"><strong>Example 13.2 (<a href="#exm-rm-enzyme">Example&nbsp;<span>13.1</span></a> Continued (Expanded Context)) </strong></span>The study described in <a href="#exm-rm-enzyme">Example&nbsp;<span>13.1</span></a> was actually conducted as a cross-over study enrolling six participants. Each participant was given one form of the enzyme (determined randomly) and followed for a specified period of time at which point the amount of fecal fat (g/day) present was obtained. Following a substantial wash-out period the participant was assigned a different form of the supplement. This continued until each participant had been assigned to all four supplement forms.</p>
<p>Interest is in determining if the amount of fecal fat produced, on average, differed for any of the treatments. However, it is known that the amount of fecal fat present can vary substantially from one individual to another due to dietary preferences; researchers would like to account for the variation in the fecal fat across subjects when performing the analysis.</p>
</div>
<p><a href="#tbl-rm-enzyme-data-table-expanded">Table&nbsp;<span>13.2</span></a> provides the same data as <a href="#tbl-rm-enzyme-data-table">Table&nbsp;<span>13.1</span></a> but with the additional context given in <a href="#exm-rm-enzyme-expanded">Example&nbsp;<span>13.2</span></a> — specifically, that six participants underwent each of the four treatments.</p>
<div class="cell">
<div class="cell-output-display">
<div id="tbl-rm-enzyme-data-table-expanded" class="anchored">
<div class="table-responsive">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<caption>Table&nbsp;13.2: Fecal fat (g/day) of six participants enrolled in a cross-over study examining four types of enzyme supplement.</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Subject 1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Subject 2</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Subject 3</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Subject 4</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Subject 5</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Subject 6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Placebo</td>
<td style="text-align: right;">44.5</td>
<td style="text-align: right;">33.0</td>
<td style="text-align: right;">19.1</td>
<td style="text-align: right;">9.4</td>
<td style="text-align: right;">71.3</td>
<td style="text-align: right;">51.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Tablet</td>
<td style="text-align: right;">7.3</td>
<td style="text-align: right;">21.0</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">4.6</td>
<td style="text-align: right;">23.3</td>
<td style="text-align: right;">38.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Coated Capsule</td>
<td style="text-align: right;">12.4</td>
<td style="text-align: right;">25.6</td>
<td style="text-align: right;">22.0</td>
<td style="text-align: right;">5.8</td>
<td style="text-align: right;">68.2</td>
<td style="text-align: right;">52.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Uncoated Capsule</td>
<td style="text-align: right;">3.4</td>
<td style="text-align: right;">23.1</td>
<td style="text-align: right;">11.8</td>
<td style="text-align: right;">4.6</td>
<td style="text-align: right;">25.6</td>
<td style="text-align: right;">36.0</td>
</tr>
</tbody>
</table>
</div>
</div>


</div>
</div>
<p>The study design results in several measurements being taken on each subject; further, the researchers believe that amount of fecal fat present can vary substantially from one individual to another. This additional information suggests that observations from the same individual are associated in some way; it is therefore unreasonable to assume the errors in <a href="#eq-rm-terminology-glm">Equation&nbsp;<span>13.1</span></a> are independent of one another.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>For those familiar, you may recognize the cross-over design described in <a href="#exm-rm-enzyme-expanded">Example&nbsp;<span>13.2</span></a> as a “randomized complete block design.” Others may be familiar with the concept of “paired data,” of which <a href="#exm-rm-enzyme-expanded">Example&nbsp;<span>13.2</span></a> is a generalization. While the idea is similar, the methods discussed in this text are a more inclusive approach.</p>
</div>
</div>
<p>Why would recording multiple observations on the same subject impact the condition of independence? A cursory look at the data confirms the researchers’ beliefs: the values of fecal fat vary greatly from one participant to another, ranging from 9 to 71 g/day in some cases. However, the values of fecal fat recorded for a single participant do not tend to vary to such a degree. That is, the variability <em>between</em> participants is substantially larger than the variability <em>within</em> a participant. As suggested by the researchers, this could be explained by differences in participant diets. It is difficult to detect differences between the supplement types since the differences between subjects is so much larger.</p>
<p>To better understand why researchers would design such a study, we review attributes of good study design. Generally speaking, there are three components to any well-designed study: replication, randomization, and reduction of extraneous noise.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>A study is not poor just because it lacks one of these elements. That is, a study can provide meaningful insights even if it does not make use of each of these elements; every study is unique and should be designed to address the research objective. These elements are simply helpful in creating study designs.</p>
</div>
</div>
<div id="def-replication" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13.1 (Replication) </strong></span>Replication results from taking measurements on different units (or subjects) for which you expect the results to be similar. That is, any variability across the units is due to natural variability within the population.</p>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>The term “replication” is also used in the context of discussing whether the results of a study are replicable. While our use of the term is about replicating a measurement process within a study, this does not downplay the importance of replicating an entire study.</p>
</div>
</div>
<p>Replication allows us to estimate subject-to-subject variability. Our intuition is that more data is better; in fact, increasing the sample size (the number of <em>unique</em> subjects on which we collect data) will result in less variability in our estimates. That is, the sampling distribution for the parameter estimates will be narrower. Increased replication also leads to increased power — the ability to detect a signal when it really exists (as the null distribution will also be narrowed).</p>
<div id="def-randomization" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13.2 (Randomization) </strong></span>Randomization can refer to random <em>selection</em> or random <em>allocation</em>.</p>
<p>Random selection refers to the use of a random mechanism to select units from the population. Random selection minimizes bias.</p>
<p>Random allocation refers to the use of a random mechanism when assigning units to a specific treatment group in a controlled experiment. Random allocation eliminates confounding and permits causal interpretations.</p>
</div>
<p>There are many forms of random sampling. Some sampling schemes ensure each collection of subjects is equally likely (e.g., simple random sample), while others over-sample from underrepresented subpopulations (e.g., stratified random sample). Each scheme shares the goal of eliminating bias, making the data more representative of the target population. While random sampling is the ideal, it is not always feasible. In clinical trials, for example, patients must elect to participate, thereby making the sample not random. When a random sample is not possible, summarizing the data to ensure it is representative of the target population is critical.</p>
<p>There are many forms of random allocation. Some randomization schemes ensure each treatment group is equally likely, while others assign participants to the active treatment with a higher probability than to the placebo. Other randomization schemes, like that mentioned in <a href="#exm-rm-enzyme-expanded">Example&nbsp;<span>13.2</span></a> randomizes the <em>order</em> of treatments. Each scheme shares the goal of eliminating confounding, allowing for causal interpretations. Whenever possible, random allocation is utilized, but it is not always feasible. Perhaps most famously, it would be unethical to conduct a randomized controlled trial to investigate the link between smoking and cancer. Therefore, observational studies were utilized to establish this link.</p>
<div id="def-noise-reduction" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13.3 (Reduction of Noise) </strong></span>Reducing extraneous sources of variability can be accomplished by fixing extraneous variables or through blocking. These actions reduce the number of differences between the units under study.</p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tension between Lab Settings and Reality
</div>
</div>
<div class="callout-body-container callout-body">
<p>Scientists and engineers are trained to control unwanted sources of variability (or sources of error in the data generating process). This creates a tension between what is observed in the study (under “lab” settings) and what is observed in practice (under “real-world” settings). This tension always exists, and the proper balance depends on the goals of the researchers.</p>
</div>
</div>
<p>Intuitively, the less variation in the response, the easier it is to detect a signal. This leads naturally to saying that we could eliminate extraneous variability if the groups were <em>identical</em>; that results in using the same subjects in multiple groups, resulting in taking repeated measurements on the subjects — blocking on the participant.</p>
<div id="def-blocking" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13.4 (Blocking) </strong></span>Blocking is a way of minimizing the variability contributed by an inherent characteristic that results in dependent observations. In some cases, the blocks are the unit of observation which is sampled from a larger population, and multiple observations are taken on each unit. In other cases, the blocks are formed by grouping the units of observations according to an inherent characteristic; in these cases that shared characteristic can be thought of having a value that was sampled from a larger population.</p>
<p>In both cases, the observed blocks can be thought of as a random sample; within each block, we have multiple observations, and the observations from the same block are more similar than observations from different blocks.</p>
</div>
<p>Blocking is useful when we can identify the nuisance characteristic in advance of data collection. Blocking is a way of ensuring the treatment groups are similar because the same subjects (with respect to this particular characteristic) end up in each treatment group. We know that random allocation eliminates confounding because it ensures that, on average, treatment groups are similar. Blocking alone does not eliminate confounding; it must be combined with randomization. However, if we account for the blocking in the analysis, we are able to sharpen our estimates because not only has balance occurred, we are able to explain a portion of the variability within each treatment group.</p>
</section>
<section id="studies-with-repeated-measures" class="level2" data-number="13.2">
<h2 data-number="13.2" class="anchored" data-anchor-id="studies-with-repeated-measures"><span class="header-section-number">13.2</span> Studies with Repeated Measures</h2>
<p>Studies that have repeated measurements taken on subjects typically violate the condition of independence. While the above design concepts apply broadly, the following terminology is specific to such studies.</p>
<div id="def-repeated-measures" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13.5 (Repeated Measures) </strong></span>The phrase “repeated measures” refers to data for which the observed responses can be grouped based on some nuisance variable (typically the participant), and this grouping captures some inherent characteristic such that observations within a group tend to be more alike than observations across groups.</p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The “paired data” setting (typically studied alongside the “paired t-test”) is a special case of using blocking with two observations per block, resulting in repeated measures.</p>
</div>
</div>
<p>As discussed in <a href="#exm-rm-enzyme-expanded">Example&nbsp;<span>13.2</span></a>, the large variability in fecal fat across participants relative to the variability in fecal fat within participants can mask the treatment effect if not accounted for appropriately. From a more theoretical perspective, this difference in the variability induces a correlation structure among the error in the responses.</p>
<div id="def-correlation-structure" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13.6 (Correlation Structure) </strong></span>The correlation structure quantifies the strength and direction of the relationship between the errors in the observed responses.</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Big Idea
</div>
</div>
<div class="callout-body-container callout-body">
<p>Ignoring the correlation structure does not tend to affect the parameter estimates, but it often affects the resulting standard errors, thereby impacting confidence intervals and p-values.</p>
</div>
</div>
<p>Unfortunately, there is no way to predict the impact of ignoring the correlation structure on the standard errors of our estimates. As a result, ignoring the correlation structure could result in confidence intervals that are too wide or too narrow (and p-values that are too large or too small). In short, ignoring the correlation structure in the data can result in inappropriate inference. In order to obtain appropriate inference, we need to account for the structure in our model!</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Big Idea
</div>
</div>
<div class="callout-body-container callout-body">
<p>When the data is correlated, it must be taken into account in all aspects of the analysis, from graphics to inference.</p>
</div>
</div>
<p>In order to illustrate the impact of the correlation structure on an analysis, let us revisit visualizing the data from the digestive enzymes study. Recall that <a href="#fig-rm-terminology-enzyme-plot">Figure&nbsp;<span>13.1</span></a> visualized the data from <a href="#exm-rm-enzyme">Example&nbsp;<span>13.1</span></a> when we assumed the data came from 24 independent participants; <a href="#fig-rm-terminology-enzyme-plot-expanded">Figure&nbsp;<span>13.2</span></a> visualizes the same data with the context from <a href="#exm-rm-enzyme-expanded">Example&nbsp;<span>13.2</span></a> included — namely that there were only six participants, each measured under multiple treatments. While there are some exceptions, notice how the lines do not “mix” often; that is, some participants tend to have less fecal fat than others, regardless of the form of the supplement given. The differences between <a href="#fig-rm-terminology-enzyme-plot">Figure&nbsp;<span>13.1</span></a> and <a href="#fig-rm-terminology-enzyme-plot-expanded">Figure&nbsp;<span>13.2</span></a> highlights that the differences in the overall average response for each supplement type is small relative to the variability across participants; as a result, focusing on the overall average response alone (<a href="#fig-rm-terminology-enzyme-plot">Figure&nbsp;<span>13.1</span></a>) make it difficult to detect differences between the supplement types. However, if we examine the differences in the supplement types <em>within each participant</em> (<a href="#fig-rm-terminology-enzyme-plot-expanded">Figure&nbsp;<span>13.2</span></a>), we can see that for nearly every participant, the fecal fat is reduced with the supplement (compared to placebo). It may not be immediately obvious if there is a difference among the form of the supplement, but it seems clear that having the supplement is better than not having it. Accounting for the variability in the response across participants changes our conclusions.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-rm-terminology-enzyme-plot-expanded" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="./images/fig-rm-terminology-enzyme-plot-expanded-1.png" class="img-fluid figure-img" style="width:80.0%" alt="Six line plots, one for each subject, overlaid on same graphic."></p>
<figcaption class="figure-caption">Figure&nbsp;13.2: Fecal fat (g/day) of six participants enrolled in a cross-over study examining four types of enzyme supplement. Data from the same participant connected to illustrate the correlation structure.</figcaption>
</figure>
</div>
</div>
</div>
<p>Notice that when examining <a href="#fig-rm-terminology-enzyme-plot-expanded">Figure&nbsp;<span>13.2</span></a>, we were not interested in comparing one participant to another; our focus was still on comparing supplement types. The additional grouping was simply to account for the relationship between the observations. Not all “grouping” variables are the same. We think about variables differently depending on their role in the model for the data generating process. Loosely, we can categorize factors as either fixed or random effects.</p>
<div id="def-fixed-effect" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13.7 (Fixed Effect) </strong></span>Fixed effects are terms in the model for which we are interested in both the specific grouping levels, and we are interested in characterizing the relationship between these levels and the response.</p>
</div>
<p>The treatment/factor of interest is nearly always a fixed effect. In addition, fixed effects can include anything we want to account for in the model in such a way that if we were to repeat the study, the same levels would be visible again. In <a href="#exm-rm-enzyme-expanded">Example&nbsp;<span>13.2</span></a>, the form of the supplement is the fixed effect. If we were to repeat the study, we would still expect to use these same four levels (placebo, tablet, coated and uncoated capsule). And, we are interested in examining the impact of supplement type on the resulting fecal fat.</p>
<div id="def-random-effect" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13.8 (Random Effect) </strong></span>Random effects are terms in the model that capture the correlation induced due to an inherent characteristic that varies across the population. We are <em>not</em> interested in the specific grouping levels, and we either are not interested in the relationship with the response.</p>
</div>
<p>We are rarely interested in saying how random effects impact the response; so, the treatment/factor of interest is rarely a random effect. In <a href="#exm-rm-enzyme-expanded">Example&nbsp;<span>13.2</span></a>, the participant is a random effect. If we were to repeat the study, it is unlikely we would use these same six individuals. Instead of quantifying the difference between participants, we wanted to think about this variable because groups of observations on the same participant are more alike than observations across participants.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In order to distinguish fixed and random effects in a model, think about repeating the study; would you care if the levels of the factor were to change? Are you interested in comparing the first level to the second? If you answer “yes” to these questions, the factor is most likely a fixed effect.</p>
</div>
</div>
<p>The impacts of fixed and random effects in modeling are studied in <a href="04c-rm-mixed-models.html"><span>Chapter&nbsp;14</span></a>. In brief, regression modeling is about partitioning variability. When we are able to identify additional sources of variability (like how the response varies across individuals in the population), we are able to improve our estimation of the effects of interest.</p>
<p>In <a href="#exm-rm-enzyme-expanded">Example&nbsp;<span>13.2</span></a>, each observation is from a unique combination of the participant on which it was observed and the treatment assigned at that time (a cross-over study). This is not the only form of a study that can result in repeated measurements. Other common study designs include longitudinal studies, cross sectional studies with subsampling, and studies that utilize cluster samples.</p>
<div id="def-cross-over-study" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13.9 (Cross-Over Study) </strong></span>A cross-over study exposes each participant to multiple treatments. Whenever possible, the order of the treatments is randomly determined. This is equivalent to a randomized complete block design in which the blocks are the participants. When the treatments are believed to have a lingering effect, a wash-out period between treatments is used to minimize the impact of previous treatments on the treatment the participant is currently being exposed to.</p>
</div>
<div id="def-rcbd" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13.10 (Randomized Complete Block Design) </strong></span>A randomized complete block design is an example of a controlled experiment utilizing blocking. Each treatment is randomized to observations within blocks in such a way that every treatment is present within the block and the same number of observations are assigned to each treatment within each block.</p>
</div>
<div id="def-longitudinal-study" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13.11 (Longitudinal Study) </strong></span>A longitudinal study repeatedly measures the response on each subject at various points in time.</p>
</div>
<p>All clinical trials follow subjects over time; a longitudinal study measures the response of interest multiple times over the course of the trial, resulting in repeated measures. In a longitudinal study, interest is often in modeling the overall trajectory across subjects instead of the trajectory for subjects individually. We are generally interested in modeling the trajectory of the response over the time interval. For example, we may be interested in the size of a tumor each month for the first year after being treated with radiation.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>There are many similarities between longitudinal studies and time-series data as each follows data over time. We do see some differences. Time-series data is often focused on business applications while longitudinal studies are more common in the biological sciences. Time-series data often models a single “stream” that is quite long. Longitudinal studies have several “streams” (one for each subject), but these tend to be a bit shorter as we do not have constant follow-up. In time-series data, it is often believed that the previous response is useful in predicting the next response; in longitudinal data, we do believe there is correlation among the errors in the model, but we do not generally use the value of the previous observation itself in making the next prediction but instead model with time as the predictor.</p>
</div>
</div>
<div id="def-cross-sectional-study" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13.12 (Cross Sectional Study) </strong></span>A cross sectional study considers data from a single snapshot in time.</p>
</div>
<p>Cross sectional studies are generally what we imagine when we first learn about data collection in an introductory course. We note that individual observations in a cross sectional study may not have been taken at exactly the same time, but it is believed that time does not have an impact. For example, we might record the size of a tumor one month after treatment with radiation. While the study might enroll participants over the course of two years, we record the measurement at one snapshot in time (one month after treatment) on each participant, and we believe the participants from each year of the study should be representative of the same group.</p>
<p>Longitudinal studies clearly involve repeated measures. Whether a cross sectional study has repeated measures depends on the study design. In the biological sciences, it is common to employ subsampling in cross sectional studies.</p>
<div id="def-subsampling" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13.13 (Subsampling) </strong></span>Subsampling occurs when several measurements are taken on each subject under the same treatment, possibly at unique locations.</p>
</div>
<p>In a study with subsampling, the unit of observation is the subject itself. As an example, a person may be assigned to a particular treatment to improve eyesight. The subject’s eyesight is then measured in each eye; the person is the unit of measurement but we obtain two measurements of the response (eyesight), one corresponding to each eye. This is sometimes referred to as “pseudo-replication,” and many researchers can mistakenly believe they have a larger sample size than exists in reality; the observations recorded on the same subject are related and should not be treated as independent observations. While it is common to average the subsamples, doing so results in a loss of information compared to modeling the correlation structure on the original data.</p>
<div id="def-cluster-samples" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13.14 (Cluster Samples) </strong></span>Stratified sampling divides a population into groups and samples from within each group; in contrast, cluster sampling divides the population into groups and randomly samples a few groups and takes measurements from within the group.</p>
</div>
<p>Observations from the same cluster are typically related. For example, if we are studying the nutrition levels of citizens within a particular state, we may sample specific counties first, and then sample participants from within the chosen counties. Citizens from the same county may be related since they have similar access to healthy food options.</p>
<p>Regardless of the study design, when we recognize clusters of observations which have some relationship beyond that explained by the fixed effects of interest, we need to model that correlation structure.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>When we use the phrase “repeated measures,” we mean repeatedly measuring the same response. All regression models make use of multiple variables measured on the same subject. The models discussed in this unit refer to measuring the same response repeatedly.</p>
</div>
</div>
<p>When representing data from a repeated-measures study, it is useful to convey the correlation structure in the graphic as well (as we did in <a href="#fig-rm-terminology-enzyme-plot-expanded">Figure&nbsp;<span>13.2</span></a>). This is not always straight-forward. When the number of subjects in the study is not overwhelming, a spaghetti plot can be useful. These are particularly useful for studies that follow subjects over time and can be helpful in illustrating the trend over time.</p>
<div id="def-spaghetti-plot" class="theorem definition">
<p><span class="theorem-title"><strong>Definition 13.15 (Spaghetti Plot) </strong></span>A spaghetti plot is a scatterplot that displays the trends within a subject, highlighting the correlation structure by connecting points from the same subject.</p>
</div>
<p>Other times, using color or other aesthetics is needed to illustrate the correlation in the data.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-Vittinghoff2012" class="csl-entry" role="listitem">
Vittinghoff, Eric, David V. Glidden, Stephen C. Shiboski, and Charles E. McCulloch. 2012. <em>Regression Methods in Biostatistics: Linear Logistic, Survival, and Repeated Measures Models</em>. 2nd ed. NY: Springer-Verlag.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04a-rm.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Unit IV: Models for Repeated Measures</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./04c-rm-mixed-models.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Mixed Effects Models</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>